name: Run Powershell script 'azure-untagged-resource-script' in Azure 

on:
  schedule:
    - cron: '0 9 * * 0'

jobs:
  run-script:
    runs-on: windows-latest
  
    steps:
    - name: Run cleanup script in Azure Cloud Shell
      uses: azure/cli@2
      with:
        azcliversion: latest
        args: az cloud-shell run --command "Invoke-WebRequest https://github.com/michaelaposto/azure-untagged-resource-script/blob/main/azure-resource-cleanup.ps1 | Invoke-Expression"