name: Run Powershell script 'azure-untagged-resource-script' in Azure 

on:
  schedule:
    - cron: '0 9 * * 0'

env:
  Azure_Credentials: ${{ secrets.Azure_Credentials }}
  Script_File: untagged_Resources.ps1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-script:
    runs-on: windows-latest
  
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ env.Azure_Credentials }}

    - name: Run Powershell script
      uses: azure/powershell@v1
      with:
        inlinescript: | 
          .\${{ env.SCRIPT_FILE }}