name: Run Powershell script 'azure-untagged-resource-script' in Azure 

on: [push]

jobs:
  run-script:
    runs-on: windows-latest
  
    steps:
    - name: Run cleanup script in Azure Cloud Shell
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        az account set --subscription $AZURE_SUBSCRIPTION_ID
        az cloud-shell run --shell powershell --command "& './azure-untagged-resource-script/azure-resource-cleanup.ps1 -emailAddress ${{ secrets.EmailUser }} -emailPassword ${{ secrets.EmailPass }}'"
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Send email of script output to Azenix PAYG members
      uses: dawidd6/action-send-mail@v3
      with:
        subject: Azenix Azure PAYG - Untagged resources 
        to: michael.aposto@azenix.com.au
        body: |
          The following resources are untagged, please either tag or remove them from the subscription. 
          Regards, 
          Azenix Team
          Script Output:
          $(cat azure-resource-cleanup.ps1.output)
        attachments: azure-resource-cleanup.ps1.output   

          
