name: Run Powershell script 'azure-untagged-resource-script' in Azure 

on: [push]

jobs:
  run-script:
    runs-on: windows-latest
  
    steps:
    - name: "Az cli login"
      uses: azure/login@v1
      with:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Run cleanup script in Azure Cloud Shell
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          $GITHUB_WORKSPACE/azure-resource-cleanup.ps1 -emailAddress ${{ secrets.EmailUser }} -emailPassword ${{ secrets.EmailPass }}

