
name: Run Powershell script 'azure-untagged-resource-script' in Azure 

on: [push]

jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run cleanup script in Azure Cloud Shell
      run: |
        $GITHUB_WORKSPACE/azure-resource-cleanup.ps1 -emailAddress ${{ secrets.EMAILUSER}} -emailPassword ${{ secrets.EMAILPASS }}
