
name: Run PS script "azure-untagged-rs-script" in Azure

on: [push]

jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Run script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./azure-untagged-resource-script/azure-resource-cleanup.ps1